# Uncomment the next line to define a global platform for your project
#platform :ios, '11.2'

target 'MultiEduca' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ObjectMapper', '3.5.0'
  pod 'KDDragAndDropCollectionViews'

  target 'MultiEducaTests' do
    inherit! :search_paths

  end

end
